### ISSUE TITLE
φ関数を追加

### ISSUE THREAD

**Issue by kanra824** [habara-k/ICPCLibrary#12]
φ(n) = nと互いに素な1以上n以下の整数の個数
O(sqrt(n))

**Comment by habara-k** [comment]
p1, ..., pk をnの素因数としたとき、
n * (1 - 1/p1) * ... * (1 - 1/pk)
でもとまる（感覚としては各素因数piを約数に持つ確率が1/pi で独立。それを全部潜り抜ける確率 * n個がφ(n)に他ならない）

覚えやすいしそこまで必要はなさそう

**Comment by habara-k** [comment]
https://github.com/habara-k/ICPCLibrary/pull/47/files
で追加した
