### ISSUE TITLE
最小費用流が負辺に対応していない

### ISSUE THREAD

**Issue by habara-k** [habara-k/ICPCLibrary#28]
primal dual のポテンシャルの初期化でdijkstraを回しているため, 最初に負辺があるとポテンシャルを正しく計算できない.

**Comment by habara-k** [comment]
http://sigma425.hatenablog.com/entry/2014/10/12/122018
蟻本に書いてあるらしい.

**Comment by kanra824** [comment]
参考その2
https://snuke.hatenablog.com/entry/2017/06/07/115821

**Comment by habara-k** [comment]
そもそも負辺を貼らない！流量が決まってるので一律でコストを足して、後で引けば良いので
