### ISSUE TITLE
SegmentTreeのupdateに関数gを設定するのは再考の余地あり

### ISSUE THREAD

**Issue by habara-k** [habara-k/ICPCLibrary#35]
# 概要

| | index `i` に値`x` をset | index `i` に`x`を加算|
|--|--|--|
|現在の実装| `g = [](M a, M b){return b;}` | `g = [](M a, M b){return a+b;}` |
|提案実装| `segt.update(i, x)` | `segt.update(i, segt[i] + x)` |

# 比較
現在の実装のデメリット
- 紛らわしい（個人的な感想）
- 表現できない演算があるかも（今のところないけど）

性能
現在の実装 https://judge.yosupo.jp/submission/26419
提案実装 https://judge.yosupo.jp/submission/26421

現在の実装710ms, 提案実装711msでほぼ同速（`segt[i]`がO(1)で動作するため）

**Comment by habara-k** [comment]
cc @kanra824

**Comment by kanra824** [comment]
クエリが更新のセグ木を別に作るということ？

**Comment by habara-k** [comment]
別ではなく、上書きしようかなと思っています（更新だけでも、加算が`segt.update(i, segt[i] + x)`でできるので）

**Comment by kanra824** [comment]
やりたいことはわかったけど、面倒な演算を載せたいときにupdateのたびにいちいち書かなきゃいけなくなってめちゃくちゃ面倒になりそう
変更する理由に対してデメリットが大きすぎる気がします

**Comment by kanra824** [comment]
いやその演算は別で関数として定義すればいいか
それもうセグ木の中にしまっておけばよくない？

**Comment by habara-k** [comment]
確かに面倒な演算は大変ですね...

LazySegmentTreeの`g(M, OM)` と区別したいので、せめて名前だけでも変えたいんですけどどうですか（例えばupdateの`u`とか）

**Comment by habara-k** [comment]
変更、なし！

**Comment by kanra824** [comment]
見てへんかった　変更なしでよい？

**Comment by kanra824** [comment]
まあupdateの時の書き方を覚えればいいので...とは思う

**Comment by kanra824** [comment]
あ、gはsegmenttreeのgを考えていた
